-- total revenau generated by male and femnale
use customer_behavior;
select 
gender,
sum(purchase_amount_usd)

from dbo.customerbehavior
group by gender
order by sum(purchase_amount_usd) desc;

-- which customer use discount but still purchse more than 5000

SELECT 
    customer_id,
    discount_applied
FROM dbo.customerbehavior
WHERE discount_applied = 'YES' and purchase_amount_usd >= (select AVG(purchase_amount_usd) from dbo.customerbehavior)

SELECT 
    customer_id,
    discount_applied,
    purchase_amount_usd,
    AVG(purchase_amount_usd) OVER (PARTITION BY customer_id) AS avg_purchase_amount
FROM dbo.customerbehavior
WHERE discount_applied = 'YES'
AND purchase_amount_usd >
    AVG(purchase_amount_usd) OVER (PARTITION BY customer_id)
ORDER BY avg_purchase_amount;


WITH t AS (
    SELECT 
        customer_id,
        discount_applied,
        purchase_amount_usd,
        AVG(purchase_amount_usd) OVER (PARTITION BY customer_id) AS avg_purchase_amount
    FROM dbo.customerbehavior
    WHERE discount_applied = 'YES'
)
SELECT *
FROM t
WHERE purchase_amount_usd > avg_purchase_amount
ORDER BY avg_purchase_amount;

-- which are the top 5 products with the highest average review rating

SELECT top 5
    item_purchased,
    round(avg(review_rating),2)
FROM dbo.customerbehavior
group by 
item_purchased
order by (round(avg(review_rating),2)) DESC

-- compare the avg PURCHASE AMOunt betwenn stand and express shipping 
select 
    shipping_type,
    avg(purchase_amount_usd)

from dbo.customerbehavior
where shipping_type in ('Express', 'Standard')
group by shipping_type
order by avg(purchase_amount_usd) DESC

-- do subscribed customer spend more? compare avg spend and total reveanu between subscriber and non subscriber

select 
    subscription_status,
    count(distinct customer_id) as total_customer,
    AVG(purchase_amount_usd) as avg_spending,
    sum(purchase_amount_usd) as total_revanue
from dbo.customerbehavior
group by subscription_status

-- which 5 products have the highest percentage of purschae with discount

SELECT TOP 5    
    item_purchased,
    COUNT(CASE WHEN discount_applied = 'YES' THEN 1 END) AS discounted_purchases,
    COUNT(*) AS total_purchases,
    ROUND(
        COUNT(CASE WHEN discount_applied = 'YES' THEN 1 END) * 100.0 
        / COUNT(*),
        2
    ) AS discount_purchase_percentage
FROM dbo.customerbehavior
GROUP BY item_purchased
ORDER BY discount_purchase_percentage DESC; 

-- segment customer into new, retuning and loyal based on their 
-- number of previous purschase, and show them the count of each segment  

with customer_types as (
SELECT
    customer_id,
    previous_purchases,
    case when previous_purchases = 1 then 'New'
         when previous_purchases between 2 and 10 then 'Returning'
         else 'Loyal'
    end as Customer_segment
from dbo.customerbehavior
)
SELECT 
    Customer_segment,
    count(customer_id) as total_customer    
from customer_types
group by Customer_segment
order by count(customer_id) desc

-- Top 3 most purchsed products of each category.
with item_count as(
select 
    category,
    item_purchased,
    count(customer_id) as total_order,
    row_number() over(partition by category order by COUNT(customer_id) desc) as item_rank
from dbo.customerbehavior
group by category,
    item_purchased
)
select 
    item_rank,
    item_purchased,
    category,
    total_order
from item_count 
where item_rank <= 3

select *from dbo.customerbehavior

-- Are customers who are repeat buyers with more than 5 previous purchases also likely to subscribe

select 
    subscription_status,
    count(customer_id) as repeat_buyers
from dbo.customerbehavior
where previous_purchases > 5
group by subscription_status

-- what is the revanue contribution of each age group

SELECT
    age_group,
    sum(purchase_amount_usd)
from dbo.customerbehavior
group by age_group
order by sum(purchase_amount_usd) desc